  var a=true;
    $(document).ready(function(){
        $(".ed").hide(); 
       $("#show").click(function(){
           if(a){
            $(".ed").show(1000);
               a=false;}
           else{
        $(".ed").hide(1000);
        a=true;
           }
       });
     
            $(".ed1").hide(); 
       $("#show1").click(function(){
           if(a){
            $(".ed1").show(1000);
               a=false;}
           else{
        $(".ed1").hide(1000);
        a=true;
           }
       });
        
           $(".ed2").hide(); 
       $("#show2").click(function(){
           if(a){
            $(".ed2").show(1000);
               a=false;}
           else{
        $(".ed2").hide(1000);
        a=true;
           }
       });
           $(".ed3").hide(); 
       $("#show3").click(function(){
           if(a){
            $(".ed3").show(1000);
               a=false;}
           else{
        $(".ed3").hide(1000);
        a=true;
           }
       });
        
           $(".ed4").hide(); 
       $("#show4").click(function(){
           if(a){
            $(".ed4").show(1000);
               a=false;}
           else{
        $(".ed4").hide(1000);
        a=true;
           }
       });
        
           $(".ed5").hide(); 
       $("#show5").click(function(){
           if(a){
            $(".ed5").show(1000);
               a=false;}
           else{
        $(".ed5").hide(1000);
        a=true;
           }
       });
        
           $(".ed6").hide(); 
       $("#show6").click(function(){
           if(a){
            $(".ed6").show(1000);
               a=false;}
           else{
        $(".ed6").hide(1000);
        a=true;
           }
       });
    });